export const categories = [
    { key: 'purchases', name: 'Mercado', icon: 'shopping-cart', color: '#5636D3' },
    { key: 'food', name: 'Lanches', icon: 'coffee', color: '#FF872C' },
    { key: 'salary', name: 'Salário', icon: 'dollar-sign', color: '#12A454' },
    { key: 'car', name: 'Carro', icon: 'truck', color: '#319693' },
    { key: 'leisure', name: 'Lazer', icon: 'heart', color: '#26195C' },
    { key: 'studies', name: 'Estudos', icon: 'book', color: '#9C001A' },
    { key: 'debts', name: 'Dívidas', icon: 'divide-circle', color: '#E94A65' },
    { key: 'card', name: 'Cartão', icon: 'credit-card', color: '#290000' },
    { key: 'home', name: 'Casa', icon: 'home', color: '#E6C14C' },
    { key: 'church', name: 'Igreja', icon: 'church', color: '#60463E' },
    { key: 'sports', name: 'Esportes', icon: 'dribbble', color: '#E67E4C' },
    { key: 'music', name: 'Entretenimentos', icon: 'headphones', color: '#D103E6' },
    { key: 'love', name: 'Romances', icon: 'heart', color: '#E60384' },
    { key: 'gift', name: 'Presentes', icon: 'gift', color: '#034FE6' },
]; 